name: Deploy Hexo to GitHub Pages
 
on:
  push:
    branches:
      - main  # Replace with your default branch name
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
 
      - name: Setup Node.js 📦
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
 
      - name: Install Hexo 🔧
        run: npm install -g hexo-cli
 
      - name: Build Hexo 🏗️
        run: hexo clean && hexo generate
 
      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Hexo public directory